### ISSUE TITLE
Build Channel for Funda Wande

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri-library#13]
## Overview 

Build public channel for https://fundawande.org/learning-resources

#### Description and outcomes
Content is in pdf format

License: CC-BY (page 3 of the workbooks) 
Copyright owner: Funda Wande

**Comment by jredrejo** [comment]
Done, in review, https://studio.learningequality.org/en/channels/77da46f34a335d0dbdbd6789156f38bd 
@rtibbles https://github.com/learningequality/sushi-chef-funda-wande-english contains the cheffing code

**Comment by radinamatic** [comment]
I updated the channel to the most recent version where the note stated that 2 corrupted PDF files have been replaced, and it did fix one that I noted in my first test, but I can still see at least 2 others:

<img width="1600" alt="fundawande" src="https://github.com/learningequality/kolibri-library/assets/1457929/2850a1d1-18c4-4e96-bef7-64bba8008e5f">

<img width="1670" alt="fundawande2" src="https://github.com/learningequality/kolibri-library/assets/1457929/783f7c3d-318c-4604-81d5-ad8c864bf500">

**Comment by jredrejo** [comment]
@radinamatic thank you, Funda Wande site was really slow and some files seem to have been downloaded with problems. I've detected some but I haven't opened all of the 118 pdf files to check all of them.
I've re-downloaded these two you've found and created a new version of the channel. Please, let me know if you find any other.

**Comment by radinamatic** [comment]
So I downloaded the full channel, but to expedite checking if any of the PDF files are corrupted (I also did not have the patience to go through 100+) I used [another application](https://sourceforge.net/projects/corruptedpdfinder/) that found other 6 (they are marked `corrupted` and `maybe corrupted` in the attached report.

[CorruptedPDFinder_results.txt](https://github.com/learningequality/kolibri-library/files/14474703/CorruptedPDFinder_results.txt)

<img width="840" alt="corrupted-PDFs" src="https://github.com/learningequality/kolibri-library/assets/1457929/ed7e63c4-abd3-4fb4-9c18-c1f214580a79">


I confirmed that they cannot be opened in Firefox, so the report is probably accurate. Do you have the means of figuring out which files are those from the Studio resource file name? I can't think of the way to do it myself in Kolibri... 🤔 

There are also [other commands](https://superuser.com/questions/580887/check-if-pdf-files-are-corrupted-using-command-line-on-linux) you could use that I would have tried had I not decided to test this channel in Windows... 🤦🏽‍♀️ 
Could these be run after you download the files from the source site, and prior to uploading them to Studio?

Comes to mind that it would be an useful addition to the chef workflow in any case, checking that downloaded PDF files are not corrupted (and maybe re-trying the download), does the `ricecooker` has something to that effect, @rtibbles?

**Comment by radinamatic** [comment]
Some other points for improvements:

1. There are 2 folders named `Reading Academy`, which is confusing. One contains videos, and the other PDF files. Given that those two types of resources are presented together in the rest of the folders, can we be fully consistent here and have one `Reading Academy` folder with both?

   <img width="971" alt="fundawande3" src="https://github.com/learningequality/kolibri-library/assets/1457929/88f3a3ba-366e-4472-af69-bb1035ef11db">

2. I can understand why we may not want to create deep nested subfolders for `Term 1`, `Term 2` etc. inside `Literacy Workbooks` and `Teaching Guides`, but instead prepend the respective term to the resource name. Could we use the dash `-` instead of the slash `/` to do that? I believe it would improve the readability.

3. The order of the resources inside the `Reading for Meaning Course` folder is a bit scattered. After the modules the resources are numbered, but start with 55, then 2, 14, 23, 139, 122... And it ends with 234, 1, 7, 142. 

   <img width="525" alt="fundawande4" src="https://github.com/learningequality/kolibri-library/assets/1457929/9ca860dc-1dac-4f45-9312-d5892d7f7a6d">
   
   I understand not all may be available in English, but could we at least have them in the proper ascending order, even if not fully sequential?

**Comment by jredrejo** [comment]
> So I downloaded the full channel, but to expedite checking if any of the PDF files are corrupted (I also did not have the patience to go through 100+) I used [another application](https://sourceforge.net/projects/corruptedpdfinder/) that found other 6 (they are marked `corrupted` and `maybe corrupted` in the attached report.
> 
> [CorruptedPDFinder_results.txt](https://github.com/learningequality/kolibri-library/files/14474703/CorruptedPDFinder_results.txt)
> 
> <img alt="corrupted-PDFs" width="840" src="https://private-user-images.githubusercontent.com/1457929/309584156-ed7e63c4-abd3-4fb4-9c18-c1f214580a79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDk3MjAsIm5iZiI6MTcwOTU0OTQyMCwicGF0aCI6Ii8xNDU3OTI5LzMwOTU4NDE1Ni1lZDdlNjNjNC1hYmQzLTRmYjQtOWMxOC1jMWYyMTQ1ODBhNzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMTA1MDIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWUzNzJjODE2NTU4M2MyY2U0M2M5MGQxN2Y4NzQzNTkyNDg0NzExYzZiZWY2ZGZkMzhiMzQ3OTdjOWViMDQzYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6Y-mvsY8pEmNMKYyzZrtxH4-2-c_fZqPo8ihFQ_agPk">
> I confirmed that they cannot be opened in Firefox, so the report is probably accurate. Do you have the means of figuring out which files are those from the Studio resource file name? I can't think of the way to do it myself in Kolibri... 🤔
> 
> There are also [other commands](https://superuser.com/questions/580887/check-if-pdf-files-are-corrupted-using-command-line-on-linux) you could use that I would have tried had I not decided to test this channel in Windows... 🤦🏽‍♀️ Could these be run after you download the files from the source site, and prior to uploading them to Studio?
> 
> Comes to mind that it would be an useful addition to the chef workflow in any case, checking that downloaded PDF files are not corrupted (and maybe re-trying the download), does the `ricecooker` has something to that effect, @rtibbles?

Thank you, after checking them, it was only 3 of them that were corrupted.
Also, for the ricecooker check, I think that's a good idea, could you open an issue in ricecooker for it? if not, I'll fill it

**Comment by jredrejo** [comment]
> Some other points for improvements:
> 
> 1. There are 2 folders named `Reading Academy`, which is confusing. One contains videos, and the other PDF files. Given that those two types of resources are presented together in the rest of the folders, can we be fully consistent here and have one `Reading Academy` folder with both?
>    <img alt="fundawande3" width="971" src="https://private-user-images.githubusercontent.com/1457929/309614215-88f3a3ba-366e-4472-af69-bb1035ef11db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDk3MjAsIm5iZiI6MTcwOTU0OTQyMCwicGF0aCI6Ii8xNDU3OTI5LzMwOTYxNDIxNS04OGYzYTNiYS0zNjZlLTQ0NzItYWY2OS1iYjEwMzVlZjExZGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMTA1MDIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzZiMzgyYjlkZTBlYzI2OTI2MzZiOTNlYTRkYmM5ODIyMThmYTExZTc2MTg0YzA4YTM2MjM3ZTdjMzkzMzJmYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZlOLkYW365vFPQ-o4JSX16xZg6jrFjvMSf9VEB9kQpM">

There was some trailing spaces in the name of the topic coming from errors in the original page. Fixed


> 2. I can understand why we may not want to create deep nested subfolders for `Term 1`, `Term 2` etc. inside `Literacy Workbooks` and `Teaching Guides`, but instead prepend the respective term to the resource name. Could we use the dash `-` instead of the slash `/` to do that? I believe it would improve the readability.

Actually, I don't know why dash is better than slash, but as I don't have any opinion on it, I've changed it.

> 3. The order of the resources inside the `Reading for Meaning Course` folder is a bit scattered. After the modules the resources are numbered, but start with 55, then 2, 14, 23, 139, 122... And it ends with 234, 1, 7, 142.
>    <img alt="fundawande4" width="525" src="https://private-user-images.githubusercontent.com/1457929/309615701-9ca860dc-1dac-4f45-9312-d5892d7f7a6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDk3MjAsIm5iZiI6MTcwOTU0OTQyMCwicGF0aCI6Ii8xNDU3OTI5LzMwOTYxNTcwMS05Y2E4NjBkYy0xZGFjLTRmNDUtOTMxMi1kNTg5MmQ3ZjdhNmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMTA1MDIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjA0Y2IxZDdhMDk4OGVmNWMxNWM4YTgzYjAzOGUwYjQ1YTBhZmYyNGI2ZTRlOTg5ZTBiZjJhODc0ZDkwZDdlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yFLcvX5s6CCKgonqgkMsjurBeqrlt3aygNt3sl7SEm4">
>    I understand not all may be available in English, but could we at least have them in the proper ascending order, even if not fully sequential?


In fact, they were sorted by the module, but module was not visible in the names, so I've added it.

**Comment by radinamatic** [comment]
> Thank you, after checking them, it was only 3 of them that were corrupted. 

I updated the channel locally, but there still 6 PDF files that report as corrupted in all browsers (Firefox, Chrome and Edge).
[CorruptedPDFinder_results.txt](https://github.com/learningequality/kolibri-library/files/14487344/CorruptedPDFinder_results.txt)

One weird thing happened during the update: it looked like it was performed in 2 separate tasks, one of whom failed, but upon another check to import more, channel was apparently fully downloaded with all resources on device 🤷🏽‍♀️ 

task | check
-- | --
<img width="840" alt="2024-03-04_20-03-11" src="https://github.com/learningequality/kolibri-library/assets/1457929/818dd3fc-4678-4355-99e3-a7115b6fdf72"> | <img width="960" alt="2024-03-04_22-30-22" src="https://github.com/learningequality/kolibri-library/assets/1457929/1bf9f912-6e02-4c81-b97b-2b06e4c73f03">
 

> Also, for the ricecooker check, I think that's a good idea, could you open an issue in ricecooker for it? if not, I'll fill it

[Done!](https://github.com/learningequality/ricecooker/issues/478) 🙂

**Comment by radinamatic** [comment]
> > Some other points for improvements:
> > 
> > 1. There are 2 folders named `Reading Academy`, which is confusing. One contains videos, and the other PDF files. Given that those two types of resources are presented together in the rest of the folders, can we be fully consistent here and have one `Reading Academy` folder with both?

> There was some trailing spaces in the name of the topic coming from errors in the original page. Fixed

Excellent! ✔️ 


> > 2. I can understand why we may not want to create deep nested subfolders for `Term 1`, `Term 2` etc. inside `Literacy Workbooks` and `Teaching Guides`, but instead prepend the respective term to the resource name. Could we use the dash `-` instead of the slash `/` to do that? I believe it would improve the readability.
> 
> Actually, I don't know why dash is better than slash, but as I don't have any opinion on it, I've changed it.
> 

I don't have hard empirical data on this, but suspect that all but nerdy computer people would find separating with slashes easier to read 😛 
Thank you for changing that! 🙏🏽 

> > 3. The order of the resources inside the `Reading for Meaning Course` folder is a bit scattered. After the modules the resources are numbered, but start with 55, then 2, 14, 23, 139, 122... And it ends with 234, 1, 7, 142.
> 
> In fact, they were sorted by the module, but module was not visible in the names, so I've added it.

Ok, thank you, looks less _unordered_ now! 👍🏽

**Comment by radinamatic** [comment]
I re-checked all the files that kept being reported as corrupted, and maybe corrupted, and were able to open them through Kolibri, so the content checks out, good work! 👏🏽 💯 :shipit:

**Comment by jredrejo** [comment]
@rtibbles waiting for your technical review after the good to go passes from @radinamatic & @revanthvle

**Comment by rtibbles** [comment]
This is complete - technical pieces are fine.
